In [957]:
import pandas as pd
import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt

In [958]:
movie = pd.read_csv("dataset.csv")

In [959]:
movie.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [960]:
# movie.release_date = movie.release_date.str.slice(0, 4).astype(float).round().astype(int)
movie.release_date = movie.release_date.str.slice(0, 4)


In [961]:
movie.columns = movie.columns.str.replace('date', 'year')
movie.release_year.dtype

dtype('O')

In [962]:
movie.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_year  \
0  Framed in the 1940s for the double murder of h...      94.075         1994   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408         1995   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585         1972   
3  The true story of how businessman Oskar Schind...      44.761         1993   
4  In the continuing saga of the Corleone crime f...      57.749         1974   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

**Removing null value columns. Unki zarurat nahi hai mujhe**

In [963]:
movie.dropna(inplace=True)

In [964]:
movie.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_year         0
vote_average         0
vote_count           0
dtype: int64

In [965]:
movie.groupby('genre')['id'].count()

genre
Action                                      54
Action,Adventure                            16
Action,Adventure,Animation                   3
Action,Adventure,Animation,Comedy            1
Action,Adventure,Animation,Comedy,Family     2
                                            ..
Western,History,War,Drama                    1
Western,Horror                               1
Western,Horror,Thriller                      1
Western,Mystery,Thriller,Drama               1
Western,Thriller                             1
Name: id, Length: 2123, dtype: int64

In [966]:
movie.genre.unique()

array(['Drama,Crime', 'Comedy,Drama,Romance', 'Drama,History,War', ...,
       'Action,TV Movie,Science Fiction,Comedy,Adventure',
       'Action,Science Fiction,War', 'Adventure,Fantasy,Action,Drama'],
      dtype=object)

In [967]:
movie.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_year         0
vote_average         0
vote_count           0
dtype: int64

In [968]:
# movie_genres = movie['genre'].str.get_dummies(sep=',')

# movie = pd.concat([movie, movie_genres], axis=1)

# movie


In [969]:
movie['details'] = movie['overview'] + movie['genre']
movie2 = movie.drop(columns=['overview','genre'])

In [970]:
movie2

id                                          title original_language  \
0        278                       The Shawshank Redemption                en   
1      19404                    Dilwale Dulhania Le Jayenge                hi   
2        238                                  The Godfather                en   
3        424                               Schindler's List                en   
4        240                         The Godfather: Part II                en   
...      ...                                            ...               ...   
9995   10196                             The Last Airbender                en   
9996  331446                       Sharknado 3: Oh Hell No!                en   
9997   13995                                Captain America                en   
9998    2312  In the Name of the King: A Dungeon Siege Tale                en   
9999  455957                                         Domino                en   

      popularity release_year  vote_average  vote_count  \
0         94.075         1994           8.7       21862   
1         25.408         1995           8.7        3731   
2         90.585         1972           8.7       16280   
3         44.761         1993           8.6       12959   
4         57.749         1974           8.6        9811   
...          ...          ...           ...         ...   
9995      98.322         2010           4.7        3347   
9996      12.490         2015           4.7         417   
9997      18.333         1990           4.6         332   
9998      15.159         2007           4.7         668   
9999      16.482         2019           4.6         221   

                                                details  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[9985 rows x 8 columns]

In [971]:
from sklearn.feature_extraction.text import CountVectorizer

In [972]:
countV = CountVectorizer(max_features=10000, stop_words='english')

In [973]:
countV.dtype

numpy.int64

In [974]:
Vector = countV.fit_transform(movie2['details'].values.astype('U')).toarray()
Vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [975]:
from sklearn.metrics.pairwise import cosine_similarity
simi = cosine_similarity(Vector)

In [976]:
simi

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])

In [977]:
def recommend(movies):
    index = movie2[movie2['title']==movies].index[0]
    MatchedVal = sorted(list(enumerate(simi[index])),reverse=True,key=lambda Vector:Vector[1])
    for i in MatchedVal[0:5]:
        print(movie2.iloc[i[0]].title)

In [978]:
recommend("F9")

F9
Furious 7
The Fast and the Furious
Fast & Furious 6
The Fate of the Furious


In [979]:
import pickle
# pickle.dump(movie2,open('movieL.pkl','wb'))

In [980]:
# pickle.dump(simi,open('simi.pkl','wb'))

In [981]:
pickle.load(open('simi.pkl','rb'))

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])